### ISSUE TITLE
Addresses don't match with mytherwallet,jaxx

### ISSUE THREAD

**Issue by ZebPayDhruvil** [trapp/ethereum-bip44#3]
I am trying to create addresses using Mnemonic, I went to bip32.org
Got the m, info private key created wallet using EthereumBip44.fromPrivateSeed

Can you guide if this would actually work ?

**Comment by slesolliec** [comment]
I tried to do the same thing but could not manage.
Found the npm package **eth-hd-wallet** and it worked like a breeze.

(There is surely something I miss with ethereum-bip44 ... particularly, I cannot see what is the difference between a privateSeed and a publicSeed)

**Comment by tab00** [comment]
I've found that addresses do match Jaxx when first using bitcore-mnemonic package to start from the phrase. Derivation path is m/44'/60'/0'/0 as hardcoded in this package, so it just works.

Coinomi instead uses m/44'/60'/0' so the code in the package would need to be changed to generate correct addresses for Coinomi.
