### ISSUE TITLE
Getting the private key

### ISSUE THREAD

**Issue by athenawisdoms** [trapp/ethereum-bip44#4]
`wallet.getAddress(0)` gives you the wallet address which looks good. However `wallet.getPrivateKey(0)` gives a `Buffer` object. How do you get the private key in the regular (string?) format?

**Comment by Mike-Dax** [comment]
```
console.log('address:', wallet.getAddress(0))
console.log('private key:', wallet.getPrivateKey(0).toString('hex')) // <- here you convert it to the string representation
```
