### ISSUE TITLE
Allow custom derivation path

### ISSUE THREAD

**Issue by tab00** [trapp/ethereum-bip44#6]
It seems that different wallets use different derivation paths for generating address.

I've found that with Coinomi, the derivation path should not have the "/0" at the end.
So this should be rewritten:
```
    this.parts = [
      `44'`, // bip 44
      `60'`,  // coin
      `0'`,  // wallet
      `0`    // 0 - public, 1 = private 
      // index
    ]
```
To
```
    this.parts = [
      `44'`, // bip 44
      `60'`,  // coin
      `0'`,  // wallet
      // index
    ]
```

Then the addresses match Coinomi's.

Maybe the derivation path could be made to be a parameter.

**Comment by trapp** [comment]
Thanks for the suggestion, this library has been deprecated and won't receive future updates though.
